history/urls.py
from django.urls import path

from . import views


app_name = "history"
urlpatterns = [
    path('', views.artists, name='artists'),
    path('<int:artist_id>/', views.detail, name='detail'),
    path('<int:artist_id>/addSong', views.add_song, name='add_song'),
    path('<int:artist_id>/addAlbum', views.add_album, name='add_album')

]

music/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('history/', include('history.urls')),
    path('admin/', admin.site.urls),
]

history/models.py
from django.db import models

class Artist(models.Model):
    artist_name = models.CharField(max_length=200)
    year_est = models.IntegerField()

    def __str__(self):
        return self.artist_name


class Genre(models.Model):
    genre_name = models.CharField(max_length=200)

    def __str__(self):
        return self.genre_name

class Album(models.Model):
    album_name = models.CharField(max_length=200)
    release_date = models.CharField(max_length=20)
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE)
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)

    def __str__(self):
        return self.album_name

class Song(models.Model):
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE)
    song_name = models.CharField(max_length=200)
    album = models.ForeignKey(Album, on_delete=models.CASCADE)

    def __str__(self):
        return self.song_name

history/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .models import Artist, Song, Album, Genre


def artists(request):
    artist_list = Artist.objects.order_by('-artist_name')
    context = {'artist_list': artist_list}
    return render(request, 'history/artists.html', context)

def detail(request, artist_id):
    artist = get_object_or_404(Artist, pk=artist_id)
    genre_list = Genre.objects.all()
    context = {'genre_list': genre_list, 'artist': artist}
    return render(request, 'history/detail.html', context)

def add_song(request, artist_id):
    album = get_object_or_404(Album, pk=request.POST["album"])
    artist = get_object_or_404(Artist, pk=artist_id)
    new_song = Song(song_name=request.POST["song_name"], album=album, artist=artist)
    new_song.save()
    return HttpResponseRedirect(reverse('history:detail', args=(artist.id, )))

def add_album(request, artist_id):
    genre = get_object_or_404(Genre, pk=request.POST["genre"])
    artist = get_object_or_404(Artist, pk=artist_id)
    new_album = Album(album_name=request.POST["album_name"], release_date=request.POST["release_date"], artist=artist, genre=genre)
    new_album.save()
    return HttpResponseRedirect(reverse('history:detail', args=(artist.id, )))

history/templates/history/artists.html
{% if artist_list %}
<ul>
    {% for artist in artist_list %}
        <li><a href="/history/{{ artist.id }}/">{{ artist.artist_name }}</a></li>
    {% endfor %}
</ul>
{% else %}
    <p>No artists here.</p>
{% endif %}

history/templates/history/detail.html
<h2>{{ artist.artist_name }}</h2>
<div>
  <p>Established {{ artist.year_est }}</p>
</div>

<h3>Albums:</h3>
{% for album in artist.album_set.all %}
    <h5>{{ album.album_name }}</h5>
    <ul>
    {% for song in album.song_set.all %}
        <li>{{ song.song_name }}</li>
    {% endfor %}
    </ul>
{% endfor %}

<form action="{% url 'history:add_song' artist.id %}" method="POST">
  {% csrf_token %}
  <h2>Add a Song</h2>
  <label for="song_name">Title:</label>
  <input type="text" name="song_name" id="song_name" />
  <select name="album">
    {% for album in artist.album_set.all %}
        <option value="{{ album.id }}" id="album{{ forloop.counter }}">{{album.album_name}}</option>
    {% endfor %}
  </select>
  <input type="submit" value="Add Song" />
</form>

<form action="{% url 'history:add_album' artist.id %}" method="POST">
    {% csrf_token %}
    <h2>Add an Album</h2>
    <label for="album_name">Title:</label>
    <input type="text" name="album_name" id="album_name" />
    <label for="release_date">Release Date:</label>
    <input type="text" name="release_date" id="release_date" />
    <select name="genre">
        {% for genre in genre_list %}
            <option value="{{ genre.id }}" id="genre{{ forloop.counter }}">{{genre.genre_name}}</option>
        {% endfor %}
    </select>
    <input type="submit" value="Add Album" />
</form>